---
title: "100 permutations of h2 estimation"
author: "Heather E. Wheeler"
date: "December 18, 2014"
output: html_document
---

I performed 100 resampling permutations for heritability estimation, shuffling the gene expression labels for the cross-tissue and orthogonal tissue-specific expression from the linear mixed-model (see cross-tissue_results_2014-11-25.md). Plotted in gray is the mean h2 (+/- 95% CI) of the 100 permutations and in red is the h2 from the observed data.

```{r,message=FALSE}
date <- Sys.Date()
library(dplyr)
library(ggplot2)
library(gridExtra)
se <- function(x) sqrt(var(x,na.rm=T)/sum(!is.na(x)))
"%&%" = function(a,b) paste(a,b,sep="")
mydir <- "/Users/heather/Dropbox/cross-tissue/"
tissues <- scan('tissue.list','character',sep='\t')
```
###plot all genes
```{r}
for(i in 1:length(tissues)){
  tis <- tissues[i]

  ##local only
  loconly <- read.table(mydir %&% 'GTEx_' %&% tis %&% '_h2_localonly_allgenes_100perms_2014-12-19.txt',sep='\t')
  obs <- loconly[,5]
  perms <- loconly[,6:105]
  meanperms <- rowMeans(perms,na.rm=T)
  seperms <- apply(perms,1,se)
    
  data <- data.frame(obs,meanperms,seperms)
  data <- data %>% mutate(ymin = pmax(0, meanperms - 2 * seperms), ymax = pmin(1, meanperms + 2 * seperms) )
  data <- data %>% arrange(obs) 
  data <- data[complete.cases(data),]

  p1 <- ggplot(data,aes(x=1:nrow(data),y=meanperms,ymin=ymin, ymax=ymax) ) + geom_pointrange(col='gray')+geom_point(col='gray')+ggtitle(tis %&% ' Local (Only) Heritability')
  loplot <- p1 + geom_point(data=data,aes(x=1:nrow(data),y=obs),color='red') + xlab("Genes sorted by observed h2") + ylab("h2") + ylim(0,1)
  print(loplot)
  
  ##global only
  gloonly <- read.table('GTEx_' %&% tis %&% '_h2_globalonly_allgenes_100perms_2014-12-19.txt',sep='\t')
  obs <- gloonly[,5]
  perms <- gloonly[,6:105]
  meanperms <- rowMeans(perms,na.rm=T)
  seperms <- apply(perms,1,se)
  
  data <- data.frame(obs,meanperms,seperms)
  data <- data %>% mutate(ymin = pmax(0, meanperms - 2 * seperms), ymax = pmin(1, meanperms + 2 * seperms) )
  data <- data %>% arrange(obs) 
  data <- data[complete.cases(data),]
  
  p1 <- ggplot(data,aes(x=1:nrow(data),y=meanperms,ymin=ymin, ymax=ymax) ) + geom_pointrange(col='gray')+geom_point(col='gray')+ggtitle(tis %&% ' Global (Only) Heritability')
  goplot <- p1 + geom_point(data=data,aes(x=1:nrow(data),y=obs),color='red') + xlab("Genes sorted by observed h2") + ylab("h2") + ylim(0,1)
  print(goplot)

  ##local joint
  locjoint <- read.table('GTEx_' %&% tis %&% '_h2_localjoint_allgenes_100perms_2014-12-19.txt',sep='\t')
  obs <- locjoint[,5]
  perms <- locjoint[,6:105]
  meanperms <- rowMeans(perms,na.rm=T)
  seperms <- apply(perms,1,se)
  
  data <- data.frame(obs,meanperms,seperms)
  data <- data %>% mutate(ymin = pmax(0, meanperms - 2 * seperms), ymax = pmin(1, meanperms + 2 * seperms) )
  data <- data %>% arrange(obs) 
  data <- data[complete.cases(data),]
  
  p1 <- ggplot(data,aes(x=1:nrow(data),y=meanperms,ymin=ymin, ymax=ymax) ) + geom_pointrange(col='gray')+geom_point(col='gray')+ggtitle(tis %&% ' Local (Joint) Heritability')
  ljplot <- p1 + geom_point(data=data,aes(x=1:nrow(data),y=obs),color='red') + xlab("Genes sorted by observed h2") + ylab("h2") + ylim(0,1)
  print(ljplot)
  
  ##global joint
  glojoint <- read.table('GTEx_' %&% tis %&% '_h2_globaljoint_allgenes_100perms_2014-12-19.txt',sep='\t')
  obs <- glojoint[,5]
  perms <- glojoint[,6:105]
  meanperms <- rowMeans(perms,na.rm=T)
  seperms <- apply(perms,1,se)
    
  data <- data.frame(obs,meanperms,seperms)
  data <- data %>% mutate(ymin = pmax(0, meanperms - 2 * seperms), ymax = pmin(1, meanperms + 2 * seperms) )
  data <- data %>% arrange(obs) 
  data <- data[complete.cases(data),]
  
  p1 <- ggplot(data,aes(x=1:nrow(data),y=meanperms,ymin=ymin, ymax=ymax) ) + geom_pointrange(col='gray')+geom_point(col='gray')+ggtitle(tis %&% ' Global (Joint) Heritability')
  gjplot <- p1 + geom_point(data=data,aes(x=1:nrow(data),y=obs),color='red') + xlab("Genes sorted by observed h2") + ylab("h2") + ylim(0,1)
  print(gjplot)
}
```

###plot genes w/h2 > 0.05
```{r}
for(i in 1:length(tissues)){
  tis <- tissues[i]
  
  ##local only
  loconly <- read.table(mydir %&% 'GTEx_' %&% tis %&% '_h2_localonly_allgenes_100perms_2014-12-19.txt',sep='\t')
  obs <- loconly[,5]
  perms <- loconly[,6:105]
  meanperms <- rowMeans(perms,na.rm=T)
  seperms <- apply(perms,1,se)
  
  data <- data.frame(obs,meanperms,seperms)
  data <- data %>% mutate(ymin = pmax(0, meanperms - 2 * seperms), ymax = pmin(1, meanperms + 2 * seperms) )
  data <- data %>% arrange(obs) 
  data <- data[complete.cases(data),]
  gt05 <- data[data[,1]>0.05,] ##only genes with obs h2 > 0.05

  p1 <- ggplot(gt05,aes(x=1:nrow(gt05),y=meanperms,ymin=ymin, ymax=ymax) ) + geom_pointrange(col='gray')+geom_point(col='gray')+ggtitle(tis %&% ' Local (Only) Heritability')
  losub <- p1 + geom_point(data=gt05,aes(x=1:nrow(gt05),y=obs),color='red') + xlab("Genes sorted by observed h2 > 0.05") + ylab("h2") + ylim(0,1)
  print(losub)
  
  ##global only
  gloonly <- read.table('GTEx_' %&% tis %&% '_h2_globalonly_allgenes_100perms_2014-12-19.txt',sep='\t')
  obs <- gloonly[,5]
  perms <- gloonly[,6:105]
  meanperms <- rowMeans(perms,na.rm=T)
  seperms <- apply(perms,1,se)
  
  data <- data.frame(obs,meanperms,seperms)
  data <- data %>% mutate(ymin = pmax(0, meanperms - 2 * seperms), ymax = pmin(1, meanperms + 2 * seperms) )
  data <- data %>% arrange(obs) 
  data <- data[complete.cases(data),]
  gt05 <- data[data[,1]>0.05,] ##only genes with obs h2 > 0.05
  
  p1 <- ggplot(gt05,aes(x=1:nrow(gt05),y=meanperms,ymin=ymin, ymax=ymax) ) + geom_pointrange(col='gray')+geom_point(col='gray')+ggtitle(tis %&% ' Global (Only) Heritability')
  gosub <- p1 + geom_point(data=gt05,aes(x=1:nrow(gt05),y=obs),color='red') + xlab("Genes sorted by observed h2 > 0.05") + ylab("h2") + ylim(0,1)
  print(gosub)
  
  ##local joint
  locjoint <- read.table('GTEx_' %&% tis %&% '_h2_localjoint_allgenes_100perms_2014-12-19.txt',sep='\t')
  obs <- locjoint[,5]
  perms <- locjoint[,6:105]
  meanperms <- rowMeans(perms,na.rm=T)
  seperms <- apply(perms,1,se)
  
  data <- data.frame(obs,meanperms,seperms)
  data <- data %>% mutate(ymin = pmax(0, meanperms - 2 * seperms), ymax = pmin(1, meanperms + 2 * seperms) )
  data <- data %>% arrange(obs) 
  data <- data[complete.cases(data),]
  gt05 <- data[data[,1]>0.05,] ##only genes with obs h2 > 0.05
  
  p1 <- ggplot(gt05,aes(x=1:nrow(gt05),y=meanperms,ymin=ymin, ymax=ymax) ) + geom_pointrange(col='gray')+geom_point(col='gray')+ggtitle(tis %&% ' Local (Joint) Heritability')
  ljsub <- p1 + geom_point(data=gt05,aes(x=1:nrow(gt05),y=obs),color='red') + xlab("Genes sorted by observed h2 > 0.05") + ylab("h2") + ylim(0,1)
  print(ljsub)
  
  ##global joint
  glojoint <- read.table('GTEx_' %&% tis %&% '_h2_globaljoint_allgenes_100perms_2014-12-19.txt',sep='\t')
  obs <- glojoint[,5]
  perms <- glojoint[,6:105]
  meanperms <- rowMeans(perms,na.rm=T)
  seperms <- apply(perms,1,se)
  
  data <- data.frame(obs,meanperms,seperms)
  data <- data %>% mutate(ymin = pmax(0, meanperms - 2 * seperms), ymax = pmin(1, meanperms + 2 * seperms) )
  data <- data %>% arrange(obs) 
  data <- data[complete.cases(data),]
  gt05 <- data[data[,1]>0.05,] ##only genes with obs h2 > 0.05
  
  p1 <- ggplot(gt05,aes(x=1:nrow(gt05),y=meanperms,ymin=ymin, ymax=ymax) ) + geom_pointrange(col='gray')+geom_point(col='gray')+ggtitle(tis %&% ' Global (Joint) Heritability')
  gjsub <- p1 + geom_point(data=gt05,aes(x=1:nrow(gt05),y=obs),color='red') + xlab("Genes sorted by observed h2 > 0.05") + ylab("h2") + ylim(0,1)
  print(gjsub)
}
```