---
title: "Preliminary Elastic Net Results"
author: "Heather E. Wheeler"
date: "`r Sys.time()`"
output: html_document
---

###DGN-WB Elastic Net 10-fold CV Results for gene expression prediction (SNPs within 1Mb of each gene)
####All alphas
```{r,all alphas}
library(ggplot2)
library(reshape2)
library(dplyr)
"%&%" = function(a,b) paste(a,b,sep="")
data<-read.table('~/Dropbox/elasticNet_testing/working_DGN-WB_exp_10-foldCV_1-reps_elasticNet_eachAlphaR2_hapmap2snps_chr22_2015-01-21.txt',header=T,check.names=F)
ngenes<-dim(data)[1]
data_long<-melt(data,by=gene)
p <- ggplot(data_long, aes(x = as.numeric(levels(variable))[variable] , y = value), group=gene) + geom_line(lwd = 0.5, show_guide = FALSE) + aes(color = gene) + xlab("alpha") + ylab("R2") + ggtitle("Elastic Net DGN-WB chr22 (" %&% ngenes %&% " genes)")
print(p)
topR2<-data_long[data_long$value>=0.1,]
ngenes <- length(unique(topR2$gene))
ggplot(topR2, aes(x = as.numeric(levels(variable))[variable] , y = value), group=gene) + geom_line(lwd = 0.5, show_guide = FALSE) + aes(color = gene) + xlab("alpha") + ylab("R2") + ggtitle("Elastic Net DGN-WB chr22 (" %&% ngenes %&% " genes with R2>0.1)")
```

####Best alphas
```{r,best alpha}
best<-read.table('~/Dropbox/elasticNet_testing/working_DGN-WB_exp_10-foldCV_1-reps_elasticNet_bestAlpha_hapmap2snps_predictionInfo_chr22_2015-01-21.txt',header=T)
best <- best[complete.cases(best),]
ngenes <- dim(best)[1]
ggplot(best, aes(x = alpha)) + geom_histogram(binwidth=0.05) + ggtitle("Elastic Net DGN-WB chr22 (" %&% ngenes %&% " genes)")
ggplot(best, aes(x = R2)) + geom_histogram(binwidth=0.05) + ggtitle("Elastic Net DGN-WB chr22 (" %&% ngenes %&% " genes)")
ggplot(best, aes(x = as.factor(alpha), y=R2)) + geom_boxplot() + ggtitle("Elastic Net DGN-WB chr22 (" %&% ngenes %&% " genes)") + xlab("alpha") + ylab("Best R2")
cor.test(best$R2,best$alpha,method="s")
top<-best[best$R2>=0.1,]
ngenes <- dim(top)[1]
ggplot(top, aes(x = as.factor(alpha), y=R2)) + geom_boxplot() + ggtitle("Elastic Net DGN-WB chr22 (" %&% ngenes %&% " genes with R2>0.1)") + xlab("alpha") + ylab("Best R2")
cor.test(top$R2,top$alpha,method="s")
```