---
title: "GenArch_figures2"
author: "Heather E. Wheeler"
date: "`r Sys.time()`"
output: html_document
---

```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(ggplot2)
library(reshape2)
library(dplyr)
library(tidyr)
library(GGally)
library(grid)
"%&%" = function(a,b) paste(a,b,sep="")
###can no longer mount tarbell because I lost UChicago VPN access
source('~/GitHub/PrediXmod/Paper_plots/multiplot.R')
my.dir <- '~/GitHub/GenArch/GenArchPaper/'
fig.dir <- '~/GitHub/GenArch/GenArchPaper/Figures/'
```

###Plot GTEx OTD Cross-Tissue Elastic Net results from Nick
```{r CTglmnetNick}
results <- read.table(my.dir %&% 'GTEx_glmnet_by_Nick_20150713/CrossTissue.allResults.txt',header=TRUE)
ngenesall <- length(unique(results$gene))
alpha1 <- dplyr::filter(results,alpha==1) %>% mutate(`1`=R2) %>% select(gene,`1`)
alpha95 <- dplyr::filter(results,alpha==0.95) %>% mutate(`0.95`=R2) %>% select(gene,`0.95`)
alpha50 <- dplyr::filter(results,alpha==0.50) %>% mutate(`0.50`=R2) %>% select(gene,`0.50`)
alpha05 <- dplyr::filter(results,alpha==0.05) %>% mutate(`0.05`=R2) %>% select(gene,`0.05`)
data <- inner_join(alpha05,alpha50,by='gene')
data <- inner_join(data,alpha95,by='gene')
data <- inner_join(data,alpha1,by='gene')
gdata <- gather(data,alpha,R2,2:4)
ggplot(gdata, aes(y = `1` - R2, x = `1`, group=alpha, color=alpha)) + geom_point(show_guide = TRUE) + ylab(expression(paste("R"^2, " difference (LASSO - alpha)"))) + xlab(expression(paste("R"^2, " (LASSO)"))) +ggtitle("GTEx cross-tissue (" %&% ngenesall %&% " genes)")+theme_gray(18)
```

###Plot GTEx OTD Cross-Tissue Elastic Net results by Heather
```{r CTglmnetHeather}
cten<-read.table(my.dir %&% 'cross-tissue_exp_10-foldCV_elasticNet_R2_for_ggplot2.txt',header=T,check.names=F)
ngenesall <- length(unique(cten$gene))
g_cten<-gather(cten,alpha,R2,3:5)
a<-ggplot(g_cten, aes(y = `1` - R2, x = `1`, group=alpha, color=alpha)) + geom_point(show_guide = TRUE) + ylab(expression(paste("R"^2, " difference (LASSO - alpha)"))) + xlab(expression(paste("R"^2, " (LASSO)"))) +ggtitle("GTEx cross-tissue (" %&% ngenesall %&% " genes)")+theme_gray(18)
a
```

###Plot GTEx OTD Tissue-Specific Elastic Net results from Nick
```{r TSglmnetNick}
tislist <- scan(my.dir %&% 'GTEx_glmnet_by_Nick_20150713/nine.tissue.list','c')
finalgdata <- data.frame()
for(tis in tislist){
  results <- read.table(my.dir %&% 'GTEx_glmnet_by_Nick_20150713/Tissue-specific/' %&% tis %&% '.allResults.txt',header=TRUE)
  ngenesall <- length(unique(results$gene))
  alpha1 <- dplyr::filter(results,alpha==1) %>% mutate(`1`=R2) %>% select(gene,`1`)
  alpha95 <- dplyr::filter(results,alpha==0.95) %>% mutate(`0.95`=R2) %>% select(gene,`0.95`)
  alpha50 <- dplyr::filter(results,alpha==0.50) %>% mutate(`0.50`=R2) %>% select(gene,`0.50`)
  alpha05 <- dplyr::filter(results,alpha==0.05) %>% mutate(`0.05`=R2) %>% select(gene,`0.05`)
  data <- inner_join(alpha05,alpha50,by='gene')
  data <- inner_join(data,alpha95,by='gene')
  data <- inner_join(data,alpha1,by='gene')
  gdata <- gather(data,alpha,R2,2:4) %>% mutate(tissue=tis)
  finalgdata <- rbind(finalgdata,gdata)
}
ggplot(finalgdata, aes(y = `1` - R2, x = `1`, group=alpha, color=alpha)) + facet_wrap(~tissue) + geom_point(show_guide = TRUE) + ylab(expression(paste("R"^2, " difference (LASSO - alpha)"))) + xlab(expression(paste("R"^2, " (LASSO)"))) +ggtitle("GTEx OTD Tissue-specific (" %&% ngenesall %&% " genes)")
```

###Plot GTEx Tissue-Wide Elastic Net results from Nick
```{r TWglmnetNick}
tislist <- scan(my.dir %&% 'GTEx_glmnet_by_Nick_20150713/nine.tissue.list','c')
finalgdata <- data.frame()
for(tis in tislist){
  results <- read.table(my.dir %&% 'GTEx_glmnet_by_Nick_20150713/Tissue-wide/' %&% tis %&% '.allResults.txt',header=TRUE)
  ngenesall <- length(unique(results$gene))
  alpha1 <- dplyr::filter(results,alpha==1) %>% mutate(`1`=R2) %>% select(gene,`1`)
  alpha95 <- dplyr::filter(results,alpha==0.95) %>% mutate(`0.95`=R2) %>% select(gene,`0.95`)
  alpha50 <- dplyr::filter(results,alpha==0.50) %>% mutate(`0.50`=R2) %>% select(gene,`0.50`)
  alpha05 <- dplyr::filter(results,alpha==0.05) %>% mutate(`0.05`=R2) %>% select(gene,`0.05`)
  data <- inner_join(alpha05,alpha50,by='gene')
  data <- inner_join(data,alpha95,by='gene')
  data <- inner_join(data,alpha1,by='gene')
  gdata <- gather(data,alpha,R2,2:4) %>% mutate(tissue=tis)
  finalgdata <- rbind(finalgdata,gdata)
}
ggplot(finalgdata, aes(y = `1` - R2, x = `1`, group=alpha, color=alpha)) + facet_wrap(~tissue) + geom_point(show_guide = TRUE) + ylab(expression(paste("R"^2, " difference (LASSO - alpha)"))) + xlab(expression(paste("R"^2, " (LASSO)"))) +ggtitle("GTEx OTD Tissue-wide (" %&% ngenesall %&% " genes)")
```