---
title: "GenArch_figures2 OTD elastic net results"
author: "Heather E. Wheeler"
date: "`r Sys.time()`"
output: html_document
---

```{r, echo=TRUE, message=FALSE, warning=FALSE}
library(ggplot2)
library(reshape2)
library(dplyr)
library(tidyr)
library(GGally)
library(grid)
"%&%" = function(a,b) paste(a,b,sep="")
###can no longer mount tarbell because I lost UChicago VPN access
source('~/GitHub/PrediXmod/Paper_plots/multiplot.R')
my.dir <- '/Volumes/im-lab/nas40t2/hwheeler/cross-tissue/gtex-OTD-CV-R2/'
fig.dir <- '~/GitHub/GenArch/GenArchPaper/Figures/'
```

###Plot GTEx OTD Cross-Tissue Elastic Net results
```{r CTglmnetHeather}
cten<-read.table(my.dir %&% 'cross-tissue_exp_10-foldCV_elasticNet_R2_for_ggplot2.txt',header=T,check.names=F)
ngenesall <- length(unique(cten$gene))
g_cten<-gather(cten,alpha,R2,3:5)
a<-ggplot(g_cten, aes(y = `1` - R2, x = `1`, group=alpha, color=alpha)) + geom_point(show_guide = TRUE) + ylab(expression(paste("R"^2, " difference (LASSO - alpha)"))) + xlab(expression(paste("R"^2, " (LASSO)"))) +ggtitle("GTEx cross-tissue (" %&% ngenesall %&% " genes)")+theme_bw(15)
a
```

###Plot GTEx OTD Tissue-Specific Elastic Net results
```{r TSglmnet}
tislist <- scan('/Volumes/im-lab/nas40t2/hwheeler/cross-tissue/nine.tissue.list','c')
finalgdata <- data.frame()
for(tis in tislist){
  alpha1 <- read.table(my.dir %&% 'TS_' %&% tis %&% '_exp_10-foldCV_elasticNet_alpha1_hapmapSnpsCEU_all_chr1-22_2015-08-27.txt',header=TRUE) %>%  mutate(`1`=R2) %>% select(gene,`1`)
  ngenesall <- length(unique(alpha1$gene))
  alpha95 <- read.table(my.dir %&% 'TS_' %&% tis %&% '_exp_10-foldCV_elasticNet_alpha0.95_hapmapSnpsCEU_all_chr1-22_2015-08-27.txt',header=TRUE) %>% mutate(`0.95`=R2) %>% select(gene,`0.95`)
  alpha50 <- read.table(my.dir %&% 'TS_' %&% tis %&% '_exp_10-foldCV_elasticNet_alpha0.5_hapmapSnpsCEU_all_chr1-22_2015-08-27.txt',header=TRUE) %>% mutate(`0.50`=R2) %>% select(gene,`0.50`)
  alpha05 <- read.table(my.dir %&% 'TS_' %&% tis %&% '_exp_10-foldCV_elasticNet_alpha0.05_hapmapSnpsCEU_all_chr1-22_2015-08-27.txt',header=TRUE) %>% mutate(`0.05`=R2) %>% select(gene,`0.05`)
  data <- inner_join(alpha05,alpha50,by='gene')
  data <- inner_join(data,alpha95,by='gene')
  data <- inner_join(data,alpha1,by='gene')
  gdata <- gather(data,alpha,R2,2:4) %>% mutate(tissue=tis)
  finalgdata <- rbind(finalgdata,gdata)
}
ggplot(finalgdata, aes(y = `1` - R2, x = `1`, group=alpha, color=alpha)) + facet_wrap(~tissue) + geom_point(show_guide = TRUE) + ylab(expression(paste("R"^2, " difference (LASSO - alpha)"))) + xlab(expression(paste("R"^2, " (LASSO)"))) +ggtitle("GTEx OTD Tissue-specific (" %&% ngenesall %&% " genes)") +theme_bw()
```

###Plot CT and TS together
```{r CTTS}
ctsort <- select(g_cten,gene,`1`,alpha,R2) %>% mutate(tissue=g_cten$`cross-tissue`)
ctts <- rbind(ctsort,finalgdata)
p<-ggplot(ctts, aes(y = `1` - R2, x = `1`, group=alpha, color=alpha)) + facet_wrap(~tissue,nrow=2) + geom_point(show_guide = TRUE) + ylab(expression(paste("R"^2, " difference (LASSO - alpha)"))) + xlab(expression(paste("R"^2, " (LASSO)"))) +ggtitle("GTEx OTD Tissue-specific (" %&% ngenesall %&% " genes)") +theme_bw(15)
p
png(filename=fig.dir %&% "Fig-GTEx_CT-TS_EN_CV.png",width=960,height=480)
p
dev.off()
tiff(filename=fig.dir %&% "Fig-GTEx_CT-TS_EN_CV.tiff",width=960,height=480)
p
dev.off()
```

###Plot GTEx Tissue-Wide Elastic Net results
```{r TWglmnet}
tislist <- scan('/Volumes/im-lab/nas40t2/hwheeler/cross-tissue/nine.tissue.list','c')
finalgdata <- data.frame()
for(tis in tislist){
  alpha1 <- read.table(my.dir %&% 'TW_' %&% tis %&% '_exp_10-foldCV_elasticNet_alpha1_hapmapSnpsCEU_all_chr1-22_2015-09-10.txt',header=TRUE) %>%  mutate(`1`=R2) %>% select(gene,`1`)
  ngenesall <- length(unique(alpha1$gene))
  alpha95 <- read.table(my.dir %&% 'TW_' %&% tis %&% '_exp_10-foldCV_elasticNet_alpha0.95_hapmapSnpsCEU_all_chr1-22_2015-09-10.txt',header=TRUE) %>% mutate(`0.95`=R2) %>% select(gene,`0.95`)
  alpha50 <- read.table(my.dir %&% 'TW_' %&% tis %&% '_exp_10-foldCV_elasticNet_alpha0.5_hapmapSnpsCEU_all_chr1-22_2015-09-10.txt',header=TRUE) %>% mutate(`0.50`=R2) %>% select(gene,`0.50`)
  alpha05 <- read.table(my.dir %&% 'TW_' %&% tis %&% '_exp_10-foldCV_elasticNet_alpha0.05_hapmapSnpsCEU_all_chr1-22_2015-09-10.txt',header=TRUE) %>% mutate(`0.05`=R2) %>% select(gene,`0.05`)
  data <- inner_join(alpha05,alpha50,by='gene')
  data <- inner_join(data,alpha95,by='gene')
  data <- inner_join(data,alpha1,by='gene')
  gdata <- gather(data,alpha,R2,2:4) %>% mutate(tissue=tis)
  finalgdata <- rbind(finalgdata,gdata)
}
p<-ggplot(finalgdata, aes(y = `1` - R2, x = `1`, group=alpha, color=alpha)) + facet_wrap(~tissue) + geom_point(show_guide = TRUE) + ylab(expression(paste("R"^2, " difference (LASSO - alpha)"))) + xlab(expression(paste("R"^2, " (LASSO)"))) +ggtitle("GTEx OTD Tissue-wide (" %&% ngenesall %&% " genes)") +theme_bw(15)
p
#ggsave(filename=fig.dir %&% "test.tiff",width=3,height=2,units = "in") I can't figure out best parameters
png(filename=fig.dir %&% "Fig-GTEx_TW_EN_CV.png",width=720,height=480)
p
dev.off()
tiff(filename=fig.dir %&% "Fig-GTEx_TW_EN_CV.tiff",width=720,height=480)
p
dev.off()
```