---
title: "TableS1-CT-TS-mean-h2"
author: "Heather Wheeler"
date: "`r Sys.time()`"
output: html_document
---

```{r, echo=TRUE, message=FALSE, warning=FALSE}
  library(ggplot2)
  library(reshape2)
  library(dplyr)
  library(tidyr)
  library(GGally)
  library(grid)
  "%&%" = function(a,b) paste(a,b,sep="")
  se <- function(x) sqrt(var(x,na.rm=TRUE)/length(is.na(x)==FALSE))
  source('/Volumes/im-lab/nas40t2/hwheeler/PrediXcan_CV/GTEx_2014-06013_release/transfers/PrediXmod/Paper_plots/multiplot.R')
  my.dir <- '/Volumes/im-lab/nas40t2/hwheeler/cross-tissue/'
  fig.dir <- '~/GitHub/GenArch/GenArchPaper/Figures/'
  rna.dir <- my.dir %&% "gtex-rnaseq/"
  annot.dir <- my.dir %&% "gtex-annot/"
  out.dir <- rna.dir %&% "ind-tissues-RPKM/"
  h2.dir <- my.dir %&% "gtex-h2-estimates/"
```

```{r, local.ts,eval=TRUE,fig.width=8,fig.height=8}
tislist <- scan(my.dir %&% '40.tissue.list',sep="\n",what="character")
table1 <- matrix(0,nrow=length(tislist)+1,ncol=6)
ct <- read.table(my.dir %&% 'cross-tissue.h2.all.models_FHSfdr0.05.Chr1-22_globaleQTLOtherChr_reml-no-constrain.2015-12-14.txt',header=T)
n <- ct$N[1]
numexpgenes <- dim(ct)[1]
#numexpgenes <- length(ct$local.p[is.na(ct$local.p)==FALSE]) 
meanh2 <- sprintf("%.3f",mean(ct$local.h2,na.rm=TRUE))
semean <- sprintf("%.4f",se(ct$local.h2))
meanandse <- meanh2 %&% " (" %&% semean %&% ")"
pest <-  ct %>%  mutate(local.q=p.adjust(local.p,method="BH")) %>% arrange(local.h2) %>% mutate(Qlt05=local.q<0.1)
propsig <- sprintf("%.1f",table(pest$Qlt05)[2]/sum(table(pest$Qlt05,useNA="i"))*100)
numsig <- table(pest$Qlt05)[2]
table1[1,] <- c("Cross-tissue",n,meanh2,propsig,numsig,numexpgenes)

for(i in 1:length(tislist)){
  tis <- tislist[i]
  data <- read.table(my.dir %&% 'GTEx.TS.' %&% tis  %&% '.h2.all.models_FHSfdr0.05.Chr1-22_globaleQTLOtherChr_reml-no-constrain.2015-12-14.txt',header=T,sep="\t")  
  n <- data$N[1]
  numexpgenes <- dim(data)[1]
  #  numexpgenes <- length(data$local.p[is.na(data$local.p)==FALSE]) ##num expressed genes mean(RPKM)>0.1
  meanh2 <- sprintf("%.3f",mean(data$local.h2,na.rm=TRUE))
  semean <- sprintf("%.4f",se(data$local.h2))
  pest <-  data %>%  mutate(local.q=p.adjust(local.p,method="BH")) %>% arrange(local.h2) %>% mutate(Qlt05=local.q<0.1) 
  propsig <- sprintf("%.2f",table(pest$Qlt05)[2]/sum(table(pest$Qlt05,useNA="i"))*100)
  numsig <- table(pest$Qlt05)[2]
  meanandse <- meanh2 %&% " (" %&% semean %&% ")"
  tableinfo <- c(tis,n,meanh2,propsig,numsig,numexpgenes)
  table1[i+1,] <- tableinfo
}
colnames(table1)=c("tissue","n","mean h2","% FDR<0.1","num FDR<0.1","num expressed")
#table1

library(xtable)
tab <- xtable(table1)
print(tab, type="latex",include.rownames=FALSE)
```


